### ISSUE TITLE
What do you think about Spain?

### ISSUE THREAD

**Issue by aarroyoc** [hackerkid/ama#10]
How do people from outside Spain thinks about Spain? and How do you think about Spain?

**Comment by hackerkid** [comment]
The first think which come to my mind when I hear about Spain is 'Football` . Your national team has a huge fan base here in India. So does Barcelona and Real Madrid. Rafael NadalI is another reason why people come across Spain in their day to day life. Personally I am also a huge fan of Cervantes because of Don Quijote. La Tomatina has made appearance in many movies in India and is also quite famous. Geographically most of us know that Spain is a small country in Europe(It's almost the same size as the state I live now). We don't know much about the politics of Spain.
